set -x
# _attn_bwd_preprocess
msprof op --kernel-name=_attn_bwd_preprocess pytest test_fwd_bwd.py::test_op[list_40]
msprof op --kernel-name=_attn_bwd_preprocess pytest test_fwd_bwd.py::test_op[list_41]
msprof op --kernel-name=_attn_bwd_preprocess pytest test_fwd_bwd.py::test_op[list_42]
msprof op --kernel-name=_attn_bwd_preprocess pytest test_fwd_bwd.py::test_op[list_43]
msprof op --kernel-name=_attn_bwd_preprocess pytest test_fwd_bwd.py::test_op[list_44]
msprof op --kernel-name=_attn_bwd_preprocess pytest test_fwd_bwd.py::test_op[list_45]
msprof op --kernel-name=_attn_bwd_preprocess pytest test_fwd_bwd.py::test_op[list_46]
msprof op --kernel-name=_attn_bwd_preprocess pytest test_fwd_bwd.py::test_op[list_47]
msprof op --kernel-name=_attn_bwd_preprocess pytest test_fwd_bwd.py::test_op[list_48]
msprof op --kernel-name=_attn_bwd_preprocess pytest test_fwd_bwd.py::test_op[list_49]
msprof op --kernel-name=_attn_bwd_preprocess pytest test_fwd_bwd.py::test_op[list_410]
msprof op --kernel-name=_attn_bwd_preprocess pytest test_fwd_bwd.py::test_op[list_411]
msprof op --kernel-name=_attn_bwd_preprocess pytest test_fwd_bwd.py::test_op[list_412]
# _attn_bwd
msprof op --kernel-name=_attn_bwd pytest test_fwd_bwd.py::test_op[list_40]
msprof op --kernel-name=_attn_bwd pytest test_fwd_bwd.py::test_op[list_41]
msprof op --kernel-name=_attn_bwd pytest test_fwd_bwd.py::test_op[list_42]
msprof op --kernel-name=_attn_bwd pytest test_fwd_bwd.py::test_op[list_43]
msprof op --kernel-name=_attn_bwd pytest test_fwd_bwd.py::test_op[list_44]
msprof op --kernel-name=_attn_bwd pytest test_fwd_bwd.py::test_op[list_45]
msprof op --kernel-name=_attn_bwd pytest test_fwd_bwd.py::test_op[list_46]
msprof op --kernel-name=_attn_bwd pytest test_fwd_bwd.py::test_op[list_47]
msprof op --kernel-name=_attn_bwd pytest test_fwd_bwd.py::test_op[list_48]
msprof op --kernel-name=_attn_bwd pytest test_fwd_bwd.py::test_op[list_49]
msprof op --kernel-name=_attn_bwd pytest test_fwd_bwd.py::test_op[list_410]
msprof op --kernel-name=_attn_bwd pytest test_fwd_bwd.py::test_op[list_411]
msprof op --kernel-name=_attn_bwd pytest test_fwd_bwd.py::test_op[list_412]